# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Exp3.xdc

# Block Designs: bd/Exp3/Exp3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Exp3 || ORIG_REF_NAME==Exp3} -quiet] -quiet

# IP: bd/Exp3/ip/Exp3_Exp3_fa2_0_0/Exp3_Exp3_fa2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Exp3_Exp3_fa2_0_0 || ORIG_REF_NAME==Exp3_Exp3_fa2_0_0} -quiet] -quiet

# IP: bd/Exp3/ip/Exp3_Exp3_fa2_0_1/Exp3_Exp3_fa2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Exp3_Exp3_fa2_0_1 || ORIG_REF_NAME==Exp3_Exp3_fa2_0_1} -quiet] -quiet

# XDC: d:/MyCode/hd2/Exp3/Exp3.gen/sources_1/bd/Exp3/Exp3_ooc.xdc
